### ISSUE TITLE
Your MazeSolver.java does not compile.

### ISSUE THREAD

**Issue by DavidHolmes0** [claremcgillis/Daedalus-Labyrinth#3]
I tried both...

* branch `v0`, which is the one you registered in the repo-of-holding; and
* branch `master` 

Am I missing sometning?

**Comment by Audrey-S00** [comment]
Thank you for notifying us with this compile issue.  We are trying to fix it right now.

**Comment by claremcgillis** [comment]
We fixed this, and it should compile now.
